!/bin/bash

# Create a echo yellow
echoyellow() { echo -e "\e[33m$1\e[0m"; }
echored()    { echo -e "\e[31m$1\e[0m"; }
echogreen()  { echo -e "\e[32m$1\e[0m"; }
echoblue()   { echo -e "\e[94m$1\e[0m"; }
echocyan()   { echo -e "\e[36m$1\e[0m"; }

echoyellow "=== Easy Install Script (DHCP Server Setup) ==="
echoyellow "This script will install and configure a DHCP server."

# Ask for user input
read -p "Enter subnet IP (e.g., 192.168.200.0): " SUBNET
read -p "Enter subnet mask (e.g., 255.255.255.0): " NETMASK
read -p "Enter broadcast address (e.g., 192.168.200.255): " BROADCAST
read -p "Enter IP range start (e.g., 192.168.200.100): " RANGE_START
read -p "Enter IP range end (e.g., 192.168.200.254): " RANGE_END
read -p "Enter default lease time in seconds (e.g., 86400 = a day): " DEFAULT_LEASE
read -p "Enter max lease time in seconds (e.g., 604800 = a week): " MAX_LEASE
read -p "Enter gateway/router IP (e.g., 192.168.200.1): " ROUTER
read -p "Enter your domain name (e.g., mydomain.local): " DOMAIN_NAME
read -p "Enter your DNS server 1 (e.g., 192.168.200.1 or 8.8.8.8 or hostname): " DNS_SERVER
read -p "Enter your DNS server 2 (e.g., 192.168.200.1 or 8.8.4.4 or hostname): " DNS_SERVER2


echoyellow ">>> Installing DHCP server package..."
dnf -y install dhcp-server

echoyellow ">>> Backing up existing DHCP configuration if present..."
if [ -f /etc/dhcp/dhcpd.conf ]; then
    cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak.$(date +%F-%H%M%S)
fi

echoyellow ">>> Writing new DHCP configuration..."
cat <<EOF > /etc/dhcp/dhcpd.conf
# DHCP Configuration generated by script
option domain-name "${DOMAIN_NAME}";
option domain-name-servers ${DNS_SERVER},${DNS_SERVER2};
default-lease-time ${DEFAULT_LEASE};
max-lease-time ${MAX_LEASE};
authoritative;
subnet ${SUBNET} netmask ${NETMASK} {
    range dynamic-bootp ${RANGE_START} ${RANGE_END};
    option broadcast-address ${BROADCAST};
    option routers ${ROUTER};
}
EOF

echoyellow ">>> Enabling and starting DHCP service..."
systemctl enable --now dhcpd

echoyellow ">>> Configuring firewall to allow DHCP traffic..."
firewall-cmd --add-service=dhcp
firewall-cmd --runtime-to-permanent

echogreen "=== DHCP server setup completed. ==="
echoblue ">>> INFORMATION."
echoblue "You can view logs here:"
echoblue " journalctl -u dhcpd -f"
echoblue "You can view active DHCP leases here:"
echoblue "  cat /var/lib/dhcpd/dhcpd.leases"
echoblue "Commands:"
echoblue "systemctl status dhcpd"
echoblue "systemctl start dhcpd"
echoblue "systemctl stop dhcpd"
echoblue "For more scripts"
echoblue "visit https://github.com/source-saraiva/" 
echoblue ">>> Done."
