#!/bin/bash

# Verbose mode on
set -x

echo "=== DHCP Server Setup Script (Linux with DNF) ==="
echo "This script will install and configure a DHCP server."

# Ask for user input
read -p "Enter your domain name (e.g., srv.world): " DOMAIN_NAME
read -p "Enter your DNS server (e.g., 10.0.0.1 or hostname): " DNS_SERVER
read -p "Enter default lease time in seconds (e.g., 86400 a day): " DEFAULT_LEASE
read -p "Enter max lease time in seconds (e.g., 604800 a week): " MAX_LEASE
read -p "Enter subnet IP (e.g., 10.0.0.0): " SUBNET
read -p "Enter subnet mask (e.g., 255.255.255.0): " NETMASK
read -p "Enter IP range start (e.g., 10.0.0.100): " RANGE_START
read -p "Enter IP range end (e.g., 10.0.0.254): " RANGE_END
read -p "Enter broadcast address (e.g., 10.0.0.255): " BROADCAST
read -p "Enter gateway/router IP (e.g., 10.0.0.1): " ROUTER

echo ">>> Installing DHCP server package..."
dnf -y install dhcp-server

echo ">>> Backing up existing DHCP configuration if present..."
if [ -f /etc/dhcp/dhcpd.conf ]; then
    cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak.$(date +%F-%H%M%S)
fi

echo ">>> Writing new DHCP configuration..."
cat <<EOF > /etc/dhcp/dhcpd.conf
# DHCP Configuration generated by script
option domain-name "${DOMAIN_NAME}";
option domain-name-servers ${DNS_SERVER};
default-lease-time ${DEFAULT_LEASE};
max-lease-time ${MAX_LEASE};
authoritative;
subnet ${SUBNET} netmask ${NETMASK} {
    range dynamic-bootp ${RANGE_START} ${RANGE_END};
    option broadcast-address ${BROADCAST};
    option routers ${ROUTER};
}
EOF

echo ">>> Enabling and starting DHCP service..."
systemctl enable --now dhcpd

echo ">>> Configuring firewall to allow DHCP traffic..."
firewall-cmd --add-service=dhcp
firewall-cmd --runtime-to-permanent

echo ">>> DHCP server setup completed."
echo "You can view active DHCP leases here:"
echo "  cat /var/lib/dhcpd/dhcpd.leases"
echo ">>> Done."
